### ISSUE TITLE
Firmware compatibilities

### ISSUE THREAD

**Issue by HadesDT** [ripleyXLR8/jeedom-plugin-gds3710#13]
Do you know if the latest firmware is compatible with your jeedom plugin ?

The firmware is the 1.0.7.8

you can found the release note here : 
[Release Note](http://firmware.grandstream.com/Release_Note_GDS3710_1.0.7.8.pdf)

**Comment by ripleyXLR8** [comment]
I'm currently writting a patch for the lastest firmware.
