### ISSUE TITLE
Envoyer un snapshot via SMS ou autre

### ISSUE THREAD

**Issue by AlpineZ33** [ripleyXLR8/jeedom-plugin-gds3710#2]
Envoyer un snapshot via SMS ou autre

Est-ce qu’il serait possible d’étendre l’envoi de snapshots via SMS (plugins JPI), mais également a l’application mobile, et autre

**Comment by ripleyXLR8** [comment]
A priori ton problème était lié au bug sur le firmware précédent. Peux-tu vérifier si ca fonctionne?
