### ISSUE TITLE
Ajout d'un deuxième bouton d'ouverture

### ISSUE THREAD

**Issue by dokime7** [ripleyXLR8/jeedom-plugin-gds3710#4]
L'un des derniers firmware ajoute la possibilité d'utiliser la sortie contact sec alarme (ALMOUT1) comme 2ème contact d'ouverture de porte permettant ainsi de pouvoir ouvrir le portail et le portillon par exemple.

Serait-il possible de l'ajouter dans le plugin ?

Le fonctionnement via l'api est exactement le même que l'ouverture du porte actuel, même authentification, même url,... la seule chose qui change pour déterminer quelle porte ouvrir c'est le remote PIN.

Il y a donc maintenant 2 remote PIN à définir dans l'interface du gds3710.

Il faudrait donc pouvoir définir ces 2 remote PIN dans l'équipement Jeedom et prévoir 2 boutons d'ouverture sur le widget.

Merci :) et bravo pour ce plugin tellement utile !

**Comment by dokime7** [comment]
Je précise que le dernier firmware 1.0.7.4 est pleinement fonctionnel avec le plugin, je n'ai pas trouvé de soucis.

**Comment by ripleyXLR8** [comment]
OK pour intégration dans la prochaine version.

**Comment by ripleyXLR8** [comment]
@dokime7 Une petite question. Je n'utilise pas cette fonctionnalité donc c'est un peu dur pour moi de tester. Dans la documentation il y a un un paramètre "opt_type" qui correspond au type de manoeuvre (ouverture ou à la fermeture). Comme il s'agit de contact sec je ne vois pas trop à quoi ça peut correspondre. Est ce que tu as une idée?

**Comment by dokime7** [comment]
Je ne sais pas non plus, dans mes tests je n'ai utilisé que le opt_type à 1 pour ouverture ayant une gâche électrique à commander.
Je ne comprends pas non plus la valeur 2...

**Comment by ripleyXLR8** [comment]
J'ai implémenté 2 nouvelles commandes ouvrir_porte_1 (qui transmet le opt_type 1) et fermer_porte_2 (qui transmet le opt_type 2). Je vais envoyer la mise à jour dans l'après-midi. Si tu peux me faire un retour sur ce que fait le fermer_porte_2 ca serait sympa.

**Comment by ripleyXLR8** [comment]
Bon finalement ta demande a été très utile. Elle va me permettre de récupérer un module zwave double contact sec qui me servait à piloter mon portail. Merci @dokime7

**Comment by dokime7** [comment]
Cool :)
Moi j'aurais du coup pas eu besoin de l'acheter, merci à toi :)
J'essaie de tester le opt_type 2 début de semaine prochaine.

**Comment by dokime7** [comment]
Je viens de faire la mise à jour :)
Je test ça quand je serai rentré chez moi.
Serait-il possible que tu ajoutes un bouton sur le widget pour ouvrir la porte 2 ?

**Comment by ripleyXLR8** [comment]
En fait normalement ça devrait déjà être le cas. Vérifie que la case "afficher" est coché à côté de la commande dans la configuration de l'équipement.

**Comment by dokime7** [comment]
En fait dans l'onglet commandes je n'ai que : ouvrir la porte (afficher coché) mais rien concernant porte 2.

**Comment by ripleyXLR8** [comment]
Tu as essayé de sauvegardé ton équipement?

**Comment by dokime7** [comment]
Je l'avais fais pour ajouter le Remote PIN 2.
Je viens de sauvegarder à nouveau à partir de l'onglet Commandes et la je viens de voir apparaitre les nouvelles commandes pour la porte 2 !!
Merci :)

**Comment by dokime7** [comment]
Et donc j'ai bien maintenant le bouton porte 2 dans le widget, nickel, merci encore :)

**Comment by ripleyXLR8** [comment]
Top. Amuse toi bien et si tu peux fait moi un petit retour sur le opt_type 2.

**Comment by dokime7** [comment]
Génial j'ai pu tester les 2 boutons d'ouverture, ça marche nickel :)
Pour le opt_type 2 je pense que c'est pour forcer la fermeture lorsqu'on utilise la fonction Keep door open (page 70 du manuel). On peut définir des heures où la porte sera ouverte, c'est dans ce cas que le opt_type 2 peut être utilisé pour fermer manuellement, enfin c'est ce que je suppose.

Je pilote une gâche de portillon donc pas utile pour moi mais j'essaierai à l'occasion de tester ça.

**Comment by ripleyXLR8** [comment]
Top. Alors on ferme le problème ;-)
