### ISSUE TITLE
No video preview

### ISSUE THREAD

**Issue by CADSSPRL** [ripleyXLR8/jeedom-plugin-gds3710#5]
Hi,
Very nice job !
I'm on latest Jeddom version and GDS plugin.
I have checked all my configuration with good documentation
Since one month, I can view video in my plugin page, button open door work correctly door work correctly.
Any idee ?
Thanks 
Christophe

**Comment by ripleyXLR8** [comment]
Hello,

Sorry for the delay. Just to be sure, you can't view the video on the widget?

Best regards,

Richard

**Comment by CADSSPRL** [comment]
Hi Richard,

Yes it's impossible see video in widget! 

Kind regards. 
Christophe 

⁣Envoyé par TypeApp ​

Le 17 sept. 2019 à 14:49, à 14:49, Richard Perez <notifications@github.com> a écrit:

**Comment by ripleyXLR8** [comment]
Could you test the content of the "Stream MJPEG" command of your equipment in Jeedom and post it here. Please hide the MAC parameter when you post it here.

**Comment by CADSSPRL** [comment]
Here you find screen capture :
Stream MJPEG is empty !
[image: image.png]
[image: image.png]

Le mar. 17 sept. 2019 à 15:12, Richard Perez <notifications@github.com> a
écrit :

**Comment by ripleyXLR8** [comment]
Sorry i cannot see your screen capture. Here is a capture of the data I need : [image](https://ibb.co/1sdv2rd)

**Comment by CADSSPRL** [comment]
Sorry hope image is visible now.
Test result is empty !

[image: 2019-09-17_17-19-52.png]

Le mar. 17 sept. 2019 à 17:11, Richard Perez <notifications@github.com> a
écrit :

**Comment by ripleyXLR8** [comment]
Nope still nothing.... but if the command result is empty try saving the equipment.

**Comment by CADSSPRL** [comment]
Already tested and full reset and re configuration of the plugin ?
Do you want a temporary access to my Jeedom ?

Le mar. 17 sept. 2019 à 17:30, Richard Perez <notifications@github.com> a
écrit :

**Comment by ripleyXLR8** [comment]
Yes please if you don't mind. Please send me an email to richard[at]perez-mail.fr.

**Comment by CADSSPRL** [comment]
I have check directly with url as it show in your attachment with mac
address, it's works !

Le mar. 17 sept. 2019 à 17:49, Christophe Antoine <cads.be@gmail.com> a
écrit :

**Comment by ripleyXLR8** [comment]
Stupid question but your MAC address is correctly filled in the equipment configuration?

**Comment by CADSSPRL** [comment]
Yes i copy paste address inserted in configuration plugin.
I have also run test directly from GDS and test succeed

Le mar. 17 sept. 2019 à 17:57, Richard Perez <notifications@github.com> a
écrit :

**Comment by ripleyXLR8** [comment]
Ok I found the issue. I think Jeedom has changed the behavior of the "event" function.
I wrote a small patch and i pushed an update.
